/** Shared auth page styles — dark premium cards */

import type { CSSProperties } from 'react'
import { colors, spacing, radius } from './design-tokens'

export const authStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: colors.bgPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing[3],
    paddingTop: `max(${spacing[3]}px, env(safe-area-inset-top))`,
    paddingBottom: `max(${spacing[3]}px, env(safe-area-inset-bottom))`,
  },
  card: {
    width: '100%',
    maxWidth: 400,
    padding: spacing[5],
    backgroundColor: colors.bgCard,
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderSubtle}`,
  },
  logo: {
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 800,
    color: colors.accent,
    marginBottom: spacing[5],
    letterSpacing: '-0.02em',
  },
  title: {
    textAlign: 'center',
    margin: `0 0 ${spacing[5]}px`,
    fontSize: 24,
    fontWeight: 800,
    color: colors.textPrimary,
    letterSpacing: '-0.02em',
  },
  form: { display: 'flex', flexDirection: 'column', gap: spacing[3] },
  inputGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
  label: { fontWeight: 500, fontSize: 14, color: colors.textSecondary },
  input: {
    padding: '14px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 16,
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    outline: 'none',
    minHeight: 56,
  },
  button: {
    padding: '14px 24px',
    backgroundColor: colors.accent,
    color: colors.textInverse,
    border: 'none',
    borderRadius: radius.md,
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: spacing[2],
    minHeight: 56,
    boxShadow: '0 4px 20px rgba(249, 115, 22, 0.28)',
  },
  error: {
    backgroundColor: colors.dangerMuted,
    color: colors.danger,
    padding: spacing[2],
    borderRadius: radius.sm,
    marginBottom: spacing[3],
    textAlign: 'center',
    fontSize: 14,
    border: `1px solid rgba(239, 68, 68, 0.2)`,
  },
  link: { textAlign: 'center', marginTop: spacing[4], color: colors.textSecondary, fontSize: 15 },
  linkColor: { color: colors.accent, textDecoration: 'none', fontWeight: 600 },
}
