/** Shared coach portal page styles */

import type { CSSProperties } from 'react'
import { colors, spacing, radius } from './design-tokens'

export const coachPageStyles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', backgroundColor: colors.bgPrimary },
  container: { maxWidth: 1200, margin: '0 auto', padding: `${spacing[4]}px ${spacing[3]}px` },
  containerNarrow: { maxWidth: 800, margin: '0 auto', padding: `${spacing[4]}px ${spacing[3]}px` },
  title: {
    margin: '0 0 6px 0',
    fontSize: 'clamp(1.5rem, 4vw, 1.85rem)',
    fontWeight: 800,
    color: colors.textPrimary,
    letterSpacing: '-0.02em',
    lineHeight: 1.15,
  },
  subtitle: { margin: '0 0 24px 0', color: colors.textSecondary, fontSize: 15, lineHeight: 1.45 },
  sectionTitle: {
    margin: 0,
    fontSize: 'clamp(1.25rem, 3.5vw, 1.5rem)',
    fontWeight: 800,
    color: colors.textPrimary,
    letterSpacing: '-0.03em',
    lineHeight: 1.2,
  },
  sectionSubtitle: {
    margin: '6px 0 0',
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 1.4,
  },
  section: {
    marginBottom: spacing[7],
  },
  backLink: { display: 'inline-block', color: colors.accent, textDecoration: 'none', marginBottom: spacing[3], fontWeight: 600, fontSize: 14 },
  loading: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '50vh', color: colors.textSecondary, backgroundColor: colors.bgPrimary },
  error: { backgroundColor: colors.dangerMuted, color: colors.danger, padding: spacing[2], borderRadius: radius.sm, marginBottom: spacing[3], fontSize: 14 },
  success: { backgroundColor: colors.successMuted, color: colors.success, padding: spacing[2], borderRadius: radius.sm, marginBottom: spacing[3], fontSize: 14 },
  card: { backgroundColor: colors.bgCard, border: `1px solid ${colors.borderSubtle}`, borderRadius: radius.md, padding: spacing[4], marginBottom: spacing[3] },
  empty: { textAlign: 'center', color: colors.textMuted, padding: `${spacing[6]}px 0` },
  searchInput: {
    flex: '1 1 220px',
    minWidth: 200,
    padding: '12px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 15,
    boxSizing: 'border-box',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minHeight: 48,
  },
  select: {
    padding: '12px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 14,
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minWidth: 160,
    minHeight: 48,
  },
  toolbar: { display: 'flex', flexWrap: 'wrap', gap: spacing[2], marginBottom: spacing[4], alignItems: 'center' },
  primaryBtn: { padding: '12px 20px', backgroundColor: colors.accent, color: colors.textInverse, border: 'none', borderRadius: radius.sm, cursor: 'pointer', fontSize: 14, fontWeight: 600, minHeight: 48 },
  secondaryBtn: { padding: '12px 20px', backgroundColor: colors.bgElevated, color: colors.textPrimary, border: `1px solid ${colors.borderSubtle}`, borderRadius: radius.sm, cursor: 'pointer', fontSize: 14, fontWeight: 600, minHeight: 48 },
  tabs: { display: 'flex', gap: 8, marginBottom: spacing[4], flexWrap: 'wrap' },
  tab: { padding: '10px 16px', borderRadius: radius.sm, border: `1px solid ${colors.borderSubtle}`, backgroundColor: colors.bgElevated, cursor: 'pointer', fontSize: 14, color: colors.textSecondary, minHeight: 44 },
  tabActive: { padding: '10px 16px', borderRadius: radius.sm, border: `1px solid ${colors.accent}`, backgroundColor: colors.accentMuted, color: colors.accent, cursor: 'pointer', fontSize: 14, fontWeight: 600, minHeight: 44 },
  listItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing[3],
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    backgroundColor: colors.bgElevated,
    marginBottom: spacing[2],
    gap: spacing[3],
    flexWrap: 'wrap',
  },
  badge: { display: 'inline-block', padding: '3px 10px', borderRadius: 12, fontSize: 12, fontWeight: 600 },
  input: {
    width: '100%',
    padding: '12px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 16,
    boxSizing: 'border-box',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minHeight: 56,
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 16,
    boxSizing: 'border-box',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    fontFamily: 'inherit',
    resize: 'vertical',
    minHeight: 120,
  },
  label: { display: 'block', marginBottom: 6, fontWeight: 500, fontSize: 14, color: colors.textSecondary },
  header: { marginBottom: spacing[4] },
  clientMain: { flex: 1 },
  clientMeta: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: spacing[2] },
  metaItem: { display: 'flex', flexDirection: 'column', gap: 4, fontSize: 14, color: colors.textPrimary },
  metaLabel: { fontSize: 12, color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: '0.5px', fontWeight: 600 },
  emptyTitle: { fontWeight: 600, fontSize: 18, marginBottom: 8, color: colors.textPrimary, margin: '0 0 8px' },
  emptyText: { color: colors.textSecondary, margin: 0 },
}
