import type { CSSProperties } from 'react'

export const aiActionStyles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', backgroundColor: '#f8f9fb' },
  container: { maxWidth: 720, margin: '0 auto', padding: '24px 20px 48px' },
  backLink: { display: 'inline-block', color: '#e94560', textDecoration: 'none', marginBottom: 16, fontWeight: 600, fontSize: 14 },
  title: { margin: '0 0 6px 0', fontSize: 26, color: '#1a1a2e' },
  subtitle: { margin: '0 0 24px 0', color: '#666', fontSize: 15 },
  sectionLabel: {
    margin: '28px 0 12px 0',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#999',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    boxShadow: '0 2px 12px rgba(26,26,46,0.06)',
    marginBottom: 12,
    border: '1px solid #eee',
  },
  actionCard: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    backgroundColor: 'white',
    border: '1px solid #e8e8e8',
    borderRadius: 12,
    padding: '16px 18px',
    marginBottom: 10,
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },
  actionCardPrimary: {
    borderColor: '#e94560',
    backgroundColor: '#fffafb',
  },
  actionCardDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  actionTitle: { margin: 0, fontSize: 16, fontWeight: 600, color: '#1a1a2e' },
  actionDesc: { margin: '4px 0 0 0', fontSize: 13, color: '#666', lineHeight: 1.45 },
  status: {
    backgroundColor: '#f0f4ff',
    color: '#1a3a6e',
    padding: '12px 14px',
    borderRadius: 10,
    fontSize: 14,
    marginBottom: 12,
  },
  error: { backgroundColor: '#fde8ea', color: '#9b1c31', padding: 12, borderRadius: 10, marginBottom: 12, fontSize: 14 },
  noteToggle: {
    background: 'none',
    border: 'none',
    color: '#666',
    fontSize: 13,
    padding: 0,
    cursor: 'pointer',
    marginBottom: 8,
    textDecoration: 'underline',
  },
  noteInput: {
    width: '100%',
    padding: 12,
    border: '1px solid #e0e0e0',
    borderRadius: 10,
    fontSize: 15,
    boxSizing: 'border-box',
    marginBottom: 16,
  },
  reasoningToggle: {
    width: '100%',
    textAlign: 'left',
    backgroundColor: '#f5f5f7',
    border: '1px solid #e8e8e8',
    borderRadius: 10,
    padding: '12px 14px',
    fontSize: 14,
    fontWeight: 600,
    color: '#333',
    cursor: 'pointer',
    marginTop: 8,
  },
  reasoningBody: {
    backgroundColor: '#fafafa',
    border: '1px solid #eee',
    borderTop: 'none',
    borderRadius: '0 0 10px 10px',
    padding: '14px 16px',
    fontSize: 13,
    color: '#444',
    lineHeight: 1.55,
    marginBottom: 12,
  },
  reasoningRow: { marginBottom: 8 },
  reasoningLabel: { color: '#999', fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.05em' },
  versionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '12px 0',
    borderBottom: '1px solid #eee',
    flexWrap: 'wrap',
  },
  versionMeta: { display: 'flex', flexDirection: 'column', gap: 4, flex: 1, minWidth: 140 },
  versionTitle: { fontWeight: 600, fontSize: 14, color: '#1a1a2e' },
  versionDate: { fontSize: 12, color: '#999' },
  badge: { fontSize: 11, fontWeight: 600, padding: '3px 8px', borderRadius: 999 },
  badgeActive: { backgroundColor: '#d4edda', color: '#155724' },
  badgeDraft: { backgroundColor: '#e7f3ff', color: '#004085' },
  badgeArchived: { backgroundColor: '#f0f0f0', color: '#666' },
  rowActions: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  linkBtn: {
    background: 'none',
    border: 'none',
    color: '#e94560',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    padding: 0,
  },
  drawerOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  drawer: {
    backgroundColor: 'white',
    width: '100%',
    maxWidth: 720,
    maxHeight: '85vh',
    overflow: 'auto',
    borderRadius: '16px 16px 0 0',
    padding: 24,
  },
  compareCol: { flex: 1, minWidth: 0 },
  comparePre: {
    whiteSpace: 'pre-wrap',
    fontSize: 12,
    lineHeight: 1.5,
    backgroundColor: '#f8f9fb',
    padding: 12,
    borderRadius: 8,
    maxHeight: 200,
    overflow: 'auto',
  },
}
