import type { CSSProperties } from 'react'
import { colors, spacing, radius } from '@/lib/coach-theme'

export const aiActionStyles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', backgroundColor: colors.bgPrimary },
  container: { maxWidth: 720, margin: '0 auto', padding: `${spacing[4]}px ${spacing[3]}px 48px` },
  backLink: { display: 'inline-block', color: colors.accent, textDecoration: 'none', marginBottom: spacing[3], fontWeight: 600, fontSize: 14 },
  title: { margin: '0 0 6px 0', fontSize: 26, color: colors.textPrimary, fontWeight: 800, letterSpacing: '-0.02em' },
  subtitle: { margin: '0 0 24px 0', color: colors.textSecondary, fontSize: 15 },
  sectionLabel: {
    margin: '28px 0 12px 0',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  card: {
    backgroundColor: colors.bgCard,
    borderRadius: radius.md,
    padding: spacing[4],
    marginBottom: spacing[2],
    border: `1px solid ${colors.borderSubtle}`,
  },
  actionCard: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.md,
    padding: '16px 18px',
    marginBottom: 10,
    cursor: 'pointer',
    transition: 'border-color 150ms ease',
    color: colors.textPrimary,
    minHeight: 64,
  },
  actionCardPrimary: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  actionCardDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  actionTitle: { margin: 0, fontSize: 16, fontWeight: 600, color: colors.textPrimary },
  actionDesc: { margin: '4px 0 0 0', fontSize: 13, color: colors.textSecondary, lineHeight: 1.45 },
  status: {
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    padding: '12px 14px',
    borderRadius: radius.sm,
    fontSize: 14,
    marginBottom: spacing[2],
  },
  statusSuccess: {
    backgroundColor: colors.successMuted,
    color: colors.success,
    padding: '12px 14px',
    borderRadius: radius.sm,
    fontSize: 14,
    marginBottom: spacing[2],
  },
  statusError: {
    backgroundColor: colors.dangerMuted,
    color: colors.danger,
    padding: '12px 14px',
    borderRadius: radius.sm,
    fontSize: 14,
    marginBottom: spacing[2],
  },
  error: { backgroundColor: colors.dangerMuted, color: colors.danger, padding: spacing[2], borderRadius: radius.sm, marginBottom: spacing[2], fontSize: 14 },
  noteToggle: {
    background: 'none',
    border: 'none',
    color: colors.textMuted,
    fontSize: 13,
    padding: 0,
    cursor: 'pointer',
    marginBottom: 8,
    textDecoration: 'underline',
  },
  noteInput: {
    width: '100%',
    padding: 12,
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 15,
    boxSizing: 'border-box',
    marginBottom: spacing[3],
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minHeight: 56,
  },
  reasoningToggle: {
    width: '100%',
    textAlign: 'left',
    backgroundColor: colors.bgElevated,
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    padding: '12px 14px',
    fontSize: 14,
    fontWeight: 600,
    color: colors.textPrimary,
    cursor: 'pointer',
    marginTop: 8,
    minHeight: 48,
  },
  reasoningBody: {
    backgroundColor: colors.bgElevated,
    border: `1px solid ${colors.borderSubtle}`,
    borderTop: 'none',
    borderRadius: '0 0 10px 10px',
    padding: '14px 16px',
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 1.55,
    marginBottom: spacing[2],
  },
  reasoningRow: { marginBottom: 8 },
  reasoningLabel: { color: colors.textMuted, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.05em' },
  versionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '12px 0',
    borderBottom: `1px solid ${colors.divider}`,
    flexWrap: 'wrap',
  },
  versionMeta: { display: 'flex', flexDirection: 'column', gap: 4, flex: 1, minWidth: 140 },
  versionTitle: { fontWeight: 600, fontSize: 14, color: colors.textPrimary },
  versionDate: { fontSize: 12, color: colors.textMuted },
  badge: { fontSize: 11, fontWeight: 600, padding: '3px 8px', borderRadius: 999 },
  badgeActive: { backgroundColor: colors.successMuted, color: colors.success },
  badgeDraft: { backgroundColor: colors.accentMuted, color: colors.accent },
  badgeArchived: { backgroundColor: colors.bgElevated, color: colors.textMuted },
  rowActions: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  linkBtn: {
    background: 'none',
    border: 'none',
    color: colors.accent,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    padding: 0,
    minHeight: 44,
  },
  drawerOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  drawer: {
    backgroundColor: colors.bgCard,
    width: '100%',
    maxWidth: 720,
    maxHeight: '85vh',
    overflow: 'auto',
    borderRadius: '16px 16px 0 0',
    padding: spacing[5],
    border: `1px solid ${colors.borderSubtle}`,
  },
  compareCol: { flex: 1, minWidth: 0 },
  comparePre: {
    whiteSpace: 'pre-wrap',
    fontSize: 12,
    lineHeight: 1.5,
    backgroundColor: colors.bgElevated,
    padding: 12,
    borderRadius: radius.sm,
    maxHeight: 200,
    overflow: 'auto',
    color: colors.textSecondary,
    border: `1px solid ${colors.borderSubtle}`,
  },
}
