import type { OnboardingFormData } from '../src/types/database'

export type LifestyleScenario = {
  id: string
  label: string
  /** What this scenario is trying to catch. */
  intent: string
  form: Partial<OnboardingFormData> & { name: string }
  /** Distinctive foods from THIS client's life that should show up. */
  mustInclude: string[]
  /** Foods / styles that would mean the plan ignored their lifestyle. */
  mustExclude: string[]
  skipBreakfast?: boolean
  skipLunch?: boolean
  requireSnack?: boolean
  lowBudget?: boolean
  sameDaily?: boolean
  fastingWeekday?: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'
}

/** 20 scenarios that cover the main real-world traps without overlapping twins. */
export const FINAL_20_SCENARIO_IDS = [
  'office-canteen-veg',
  'night-shift-nurse',
  'hostel-mess-vegan',
  'if-skip-breakfast',
  'jain-no-root',
  'lactose-veg-no-dairy',
  'nut-allergy-vegan',
  'gluten-sensitive',
  'eggs-mwf-only',
  'chicken-tue-thu-fish-sun',
  'ultra-budget-dal-rice',
  'south-indian-staples',
  'bengali-fish-rice',
  'late-it-shift',
  'busy-parent-leftovers',
  'street-food-mumbai',
  'tuesday-fast',
  'vegan-south-no-ghee',
  'labour-physical-job',
  'dislikes-plus-allergy-stack',
] as const

export function finalSmokeScenarios(): LifestyleScenario[] {
  const byId = new Map(LIFESTYLE_SCENARIOS.map((s) => [s.id, s]))
  return FINAL_20_SCENARIO_IDS.map((id) => {
    const hit = byId.get(id)
    if (!hit) throw new Error(`Unknown lifestyle scenario: ${id}`)
    return hit
  })
}

const dietReset = {
  egg_days: '0',
  chicken_days: '0',
  fish_days: '0',
  egg_allowed_days: [] as string[],
  chicken_allowed_days: [] as string[],
  fish_allowed_days: [] as string[],
}

export const LIFESTYLE_SCENARIOS: LifestyleScenario[] = [
  {
    id: 'office-canteen-veg',
    label: 'Office canteen vegetarian, late dinner',
    intent: 'Office hours + canteen lunch + 10:30pm dinner — not a 7am home-cooked chart',
    form: {
      name: 'Karan Office',
      gender: 'male',
      age: '34',
      weight: '86',
      height: '176',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      work_school_schedule:
        'Office 10am–7pm Mon–Fri, commute 45 min. Lunch from office canteen. Evenings free after 8:30pm.',
      activity_level: 'sedentary',
      daily_steps: '3000_6000',
      training_days_per_week: '4',
      training_available_days: ['monday', 'tuesday', 'thursday', 'saturday'],
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      monthly_food_budget: '8000',
      favorite_foods: 'Canteen thali, dal, roti, sandwich',
      foods_disliked: 'Bitter gourd',
      food_allergies: 'none',
      breakfast: 'Office canteen sandwich and chai',
      lunch: 'Office thali — dal, roti, sabzi, curd',
      dinner: 'Leftover roti with dal or late delivery',
      snacks: 'Chai and roasted chana at desk',
      timing_breakfast: '09:30',
      timing_lunch: '14:00',
      timing_dinner: '22:30',
      timing_snacks: '17:00',
      diet_variety: 'same_daily',
    },
    mustInclude: ['sandwich', 'thali', 'dal', 'roti'],
    mustExclude: ['quinoa', 'avocado', 'smoothie', 'overnight oats', 'turkey'],
    requireSnack: true,
    sameDaily: true,
  },
  {
    id: 'night-shift-nurse',
    label: 'Night-shift nurse, inverted meals',
    intent: 'Post-shift 7am meal and pre-shift dinner — not a standard 8/1/8 chart',
    form: {
      name: 'Divya Nightshift',
      gender: 'female',
      age: '31',
      weight: '71',
      height: '162',
      fitness_goal: 'fat_loss',
      occupation: 'shift_work',
      work_school_schedule: 'Hospital night shifts 10pm–6am four days a week. Sleeps 8am–3pm. Off days inverted.',
      sleep_duration: 'less_than_6',
      training_days_per_week: '3',
      training_available_days: ['tuesday', 'thursday', 'saturday'],
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      favorite_foods: 'Paratha, dal, rice, chai',
      breakfast: 'Post-shift paratha and chai',
      lunch: 'I sleep through lunch on shift days — skip it',
      dinner: 'Pre-shift rice, dal, and sabzi',
      snacks: 'Hospital canteen biscuits or banana',
      timing_breakfast: '07:00',
      timing_lunch: '',
      timing_dinner: '20:00',
      timing_snacks: '02:00',
      foods_disliked: 'Mushrooms',
      food_allergies: 'none',
    },
    mustInclude: ['paratha', 'chai', 'dal', 'rice'],
    mustExclude: ['quinoa', 'overnight oats', 'smoothie bowl'],
    skipLunch: true,
  },
  {
    id: 'hostel-mess-vegan',
    label: 'Hostel mess vegan, no cooking, tight budget',
    intent: 'Mess food only — no elaborate home cooking, no expensive foods',
    form: {
      name: 'Aarav Hostel',
      gender: 'male',
      age: '20',
      weight: '64',
      height: '174',
      fitness_goal: 'muscle_gain',
      occupation: 'student',
      work_school_schedule: 'College 9am–4pm. Hostel mess for all meals. No kitchen access.',
      diet_preference: 'vegan',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'minimal',
      monthly_food_budget: '4000',
      favorite_foods: 'Mess dal, rice, roti, poha',
      breakfast: 'Hostel mess poha or bread',
      lunch: 'Mess rice, dal, and sabzi',
      dinner: 'Mess roti and mixed veg',
      snacks: 'Banana from canteen',
      timing_breakfast: '08:00',
      timing_lunch: '13:00',
      timing_dinner: '20:00',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['poha', 'dal', 'rice', 'roti'],
    mustExclude: ['quinoa', 'avocado', 'tofu scramble', 'smoothie', 'tempeh', 'imported'],
    lowBudget: true,
    requireSnack: true,
  },
  {
    id: 'if-skip-breakfast',
    label: 'Intermittent fasting — skips breakfast',
    intent: 'Must not invent a 7–9am breakfast slot',
    form: {
      name: 'Neha Fasting',
      gender: 'female',
      age: '29',
      weight: '68',
      height: '164',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      favorite_foods: 'Dal, roti, paneer, rice',
      breakfast: 'I skip breakfast. First meal is lunch.',
      lunch: 'Dal, roti, salad, and curd',
      dinner: 'Paneer or dal with roti',
      snacks: 'Tea with roasted chana around 4pm',
      timing_breakfast: '',
      timing_lunch: '12:30',
      timing_dinner: '20:00',
      timing_snacks: '16:30',
      diet_custom_notes: '16:8 intermittent fasting. No calories before 12:30pm.',
      food_allergies: 'none',
      foods_disliked: 'Olives',
    },
    mustInclude: ['dal', 'roti'],
    mustExclude: ['overnight oats', '7:00', '07:00', '8:00 breakfast'],
    skipBreakfast: true,
    requireSnack: true,
  },
  {
    id: 'jain-no-root',
    label: 'Jain vegetarian — no onion garlic potato',
    intent: 'Jain constraint must not be ignored with aloo/onion/garlic meals',
    form: {
      name: 'Meera Jain',
      gender: 'female',
      age: '36',
      weight: '62',
      height: '160',
      fitness_goal: 'fat_loss',
      occupation: 'homemaker',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'comfortable',
      favorite_foods: 'Dal, steamed rice, doodhi, cabbage sabzi, thepla',
      breakfast: 'Thepla with chutney (no onion garlic)',
      lunch: 'Dal, rice, and doodhi sabzi',
      dinner: 'Roti with cabbage or tinda sabzi',
      snacks: 'Fruit and roasted chana',
      timing_breakfast: '08:30',
      timing_lunch: '13:30',
      timing_dinner: '20:30',
      timing_snacks: '17:30',
      foods_disliked: 'Onion, garlic, potato',
      diet_custom_notes: 'Jain — no onion, garlic, or root vegetables (potato, onion, garlic, carrot, beetroot).',
      food_allergies: 'none',
    },
    mustInclude: ['dal', 'thepla', 'doodhi'],
    mustExclude: ['onion', 'garlic', 'potato', 'aloo', 'carrot'],
  },
  {
    id: 'lactose-veg-no-dairy',
    label: 'Lactose-intolerant vegetarian',
    intent: 'Must not use paneer, curd, milk, whey, cheese',
    form: {
      name: 'Priya Lactose',
      gender: 'female',
      age: '27',
      weight: '66',
      height: '163',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      food_allergies: 'Lactose intolerant',
      favorite_foods: 'Poha, dal, roti, soya, chana',
      breakfast: 'Poha with peanuts',
      lunch: 'Dal, roti, and salad',
      dinner: 'Soya chunks curry with roti',
      snacks: 'Roasted chana',
      timing_breakfast: '08:00',
      timing_lunch: '13:30',
      timing_dinner: '21:00',
      timing_snacks: '17:00',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['poha', 'dal', 'soya'],
    mustExclude: ['paneer', 'curd', 'dahi', 'cheese', 'whey', 'milkshake', 'yogurt'],
  },
  {
    id: 'nut-allergy-vegan',
    label: 'Vegan with nut allergy',
    intent: 'No peanut/almond/cashew even as “healthy snacks”',
    form: {
      name: 'Isha Nuts',
      gender: 'female',
      age: '25',
      weight: '58',
      height: '161',
      fitness_goal: 'body_recomposition',
      occupation: 'student',
      diet_preference: 'vegan',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      food_allergies: 'Nut allergy',
      favorite_foods: 'Idli, sambar, dal, rice, roti',
      breakfast: 'Idli with sambar',
      lunch: 'Dal, rice, and salad',
      dinner: 'Chole with roti',
      snacks: 'Roasted chana and fruit',
      timing_breakfast: '08:00',
      timing_lunch: '13:00',
      timing_dinner: '20:30',
      timing_snacks: '16:30',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['idli', 'sambar', 'dal'],
    mustExclude: ['peanut', 'almond', 'cashew', 'walnut', 'nut butter'],
  },
  {
    id: 'gluten-sensitive',
    label: 'Gluten-sensitive vegetarian',
    intent: 'Must not default to roti/paratha/wheat bread',
    form: {
      name: 'Rohan Gluten',
      gender: 'male',
      age: '33',
      weight: '78',
      height: '175',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'comfortable',
      food_allergies: 'Gluten allergy / celiac',
      favorite_foods: 'Rice, dal, idli, poha, sabzi',
      breakfast: 'Poha or idli',
      lunch: 'Rice, dal, and sabzi',
      dinner: 'Rice with dal tadka and vegetables',
      snacks: 'Fruit bowl',
      timing_breakfast: '08:30',
      timing_lunch: '13:30',
      timing_dinner: '20:30',
      timing_snacks: '17:00',
      foods_disliked: 'None',
    },
    mustInclude: ['rice', 'dal', 'poha'],
    mustExclude: ['roti', 'paratha', 'atta', 'wheat bread', 'chapati', 'naan'],
  },
  {
    id: 'eggs-mwf-only',
    label: 'Eggetarian — eggs only Mon/Wed/Fri',
    intent: 'Eggs must not appear on Tue/Thu/Sat/Sun',
    form: {
      name: 'Aditya Eggs',
      gender: 'male',
      age: '26',
      weight: '72',
      height: '178',
      fitness_goal: 'muscle_gain',
      occupation: 'desk_job',
      diet_preference: 'eggetarian',
      egg_days: '3',
      chicken_days: '0',
      fish_days: '0',
      egg_allowed_days: ['monday', 'wednesday', 'friday'],
      chicken_allowed_days: [],
      fish_allowed_days: [],
      whey_protein: 'yes',
      cooking_ability: 'basic',
      favorite_foods: 'Eggs, dal, roti, oats',
      breakfast: 'Egg bhurji with roti on egg days, else poha',
      lunch: 'Dal, roti, and salad',
      dinner: 'Egg curry or dal with roti',
      snacks: 'Roasted chana',
      timing_breakfast: '08:00',
      timing_lunch: '13:30',
      timing_dinner: '21:00',
      timing_snacks: '17:30',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
      preferred_workout_time: 'evening',
    },
    mustInclude: ['egg', 'dal', 'roti'],
    mustExclude: ['chicken', 'fish', 'mutton'],
  },
  {
    id: 'chicken-tue-thu-fish-sun',
    label: 'Non-veg — chicken Tue/Thu, fish Sunday only',
    intent: 'Chicken/fish must not leak onto veg weekdays',
    form: {
      name: 'Vikram Nonveg',
      gender: 'male',
      age: '30',
      weight: '82',
      height: '180',
      fitness_goal: 'muscle_gain',
      occupation: 'physical_job',
      diet_preference: 'non_vegetarian',
      egg_days: '2',
      chicken_days: '2',
      fish_days: '1',
      egg_allowed_days: ['monday', 'wednesday'],
      chicken_allowed_days: ['tuesday', 'thursday'],
      fish_allowed_days: ['sunday'],
      whey_protein: 'yes',
      cooking_ability: 'basic',
      favorite_foods: 'Chicken curry, rice, dal, eggs',
      breakfast: 'Eggs and toast on egg days, else poha',
      lunch: 'Rice, dal, and sabzi — chicken only Tue/Thu',
      dinner: 'Roti with sabzi, fish only Sunday',
      snacks: 'Buttermilk and chana',
      timing_breakfast: '07:30',
      timing_lunch: '13:00',
      timing_dinner: '20:30',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['dal', 'rice', 'chicken'],
    mustExclude: ['mutton', 'prawn', 'beef'],
  },
  {
    id: 'same-meals-daily',
    label: 'Same meals every day (poha / dal-roti)',
    intent: 'Must not invent a 7-day variety chart',
    form: {
      name: 'Sneha Repeat',
      gender: 'female',
      age: '28',
      weight: '64',
      height: '158',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      diet_variety: 'same_daily',
      favorite_foods: 'Poha, dal, roti, curd',
      breakfast: 'Poha with peanuts every day',
      lunch: 'Dal, two rotis, and sabzi every day',
      dinner: 'Dal, roti, and salad every day',
      snacks: 'Curd with fruit',
      timing_breakfast: '08:30',
      timing_lunch: '13:30',
      timing_dinner: '20:30',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['poha', 'dal', 'roti'],
    mustExclude: ['quinoa', 'smoothie', 'overnight oats', 'avocado toast'],
    sameDaily: true,
  },
  {
    id: 'ultra-budget-dal-rice',
    label: '₹4000/month — dal rice roti only',
    intent: 'Must not prescribe expensive / imported foods',
    form: {
      name: 'Ravi Budget',
      gender: 'male',
      age: '29',
      weight: '76',
      height: '172',
      fitness_goal: 'fat_loss',
      occupation: 'physical_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      monthly_food_budget: '4000',
      favorite_foods: 'Dal, rice, seasonal sabzi, roti',
      breakfast: 'Leftover roti with pickle or chai and biscuits',
      lunch: 'Rice and dal',
      dinner: 'Roti and seasonal sabzi',
      snacks: 'Roasted chana',
      timing_breakfast: '07:30',
      timing_lunch: '13:00',
      timing_dinner: '21:00',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'None',
    },
    mustInclude: ['dal', 'rice', 'roti'],
    mustExclude: ['avocado', 'quinoa', 'salmon', 'berries', 'almond butter', 'protein bar', 'sushi'],
    lowBudget: true,
  },
  {
    id: 'south-indian-staples',
    label: 'South Indian home — idli dosa sambar rice',
    intent: 'Must build from idli/dosa/sambar/rice, not North Indian default chart',
    form: {
      name: 'Ananya South',
      gender: 'female',
      age: '32',
      weight: '70',
      height: '165',
      fitness_goal: 'fat_loss',
      occupation: 'homemaker',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'comfortable',
      favorite_foods: 'Idli, dosa, sambar, rasam, rice, curd rice',
      breakfast: 'Idli with sambar',
      lunch: 'Rice, sambar, rasam, and poriyal',
      dinner: 'Dosa or idli with sambar, or curd rice',
      snacks: 'Sundal or fruit',
      timing_breakfast: '08:00',
      timing_lunch: '13:30',
      timing_dinner: '20:00',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['idli', 'sambar', 'rice'],
    mustExclude: ['quinoa', 'avocado toast', 'overnight oats', 'smoothie bowl'],
  },
  {
    id: 'punjabi-home',
    label: 'Punjabi home cook — paratha, dal, paneer',
    intent: 'Must use their actual Punjabi staples, not a generic fat-loss chart',
    form: {
      name: 'Kavya Punjabi',
      gender: 'female',
      age: '35',
      weight: '74',
      height: '162',
      fitness_goal: 'fat_loss',
      occupation: 'homemaker',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'advanced',
      favorite_foods: 'Paratha, dal makhani, paneer, lassi, roti',
      breakfast: 'Aloo paratha with curd',
      lunch: 'Dal, roti, sabzi, salad',
      dinner: 'Paneer or dal with roti',
      snacks: 'Lassi or fruit',
      timing_breakfast: '09:00',
      timing_lunch: '14:00',
      timing_dinner: '21:00',
      timing_snacks: '17:30',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['paratha', 'dal', 'paneer', 'roti'],
    mustExclude: ['quinoa', 'tofu', 'smoothie bowl'],
  },
  {
    id: 'bengali-fish-rice',
    label: 'Bengali — fish and rice, fish only 3 days',
    intent: 'Rice + fish lifestyle; fish only on allowed days',
    form: {
      name: 'Dev Bengali',
      gender: 'male',
      age: '38',
      weight: '80',
      height: '171',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'non_vegetarian',
      egg_days: '0',
      chicken_days: '0',
      fish_days: '3',
      egg_allowed_days: [],
      chicken_allowed_days: [],
      fish_allowed_days: ['tuesday', 'thursday', 'sunday'],
      whey_protein: 'no',
      cooking_ability: 'comfortable',
      favorite_foods: 'Rice, macher jhol, dal, aloo posto, begun bhaja',
      breakfast: 'Puffed rice or leftover rice with dal',
      lunch: 'Rice, dal, and fish curry on fish days',
      dinner: 'Rice with dal and sabzi',
      snacks: 'Muri and tea',
      timing_breakfast: '08:30',
      timing_lunch: '14:00',
      timing_dinner: '21:30',
      timing_snacks: '18:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['rice', 'dal', 'fish'],
    mustExclude: ['chicken', 'mutton', 'quinoa'],
  },
  {
    id: 'gujarati-thepla-khichdi',
    label: 'Gujarati — thepla, khichdi, dal dhokli',
    intent: 'Must not swap their Gujarati staples for a generic North Indian chart',
    form: {
      name: 'Isha Gujarati',
      gender: 'female',
      age: '41',
      weight: '69',
      height: '157',
      fitness_goal: 'fat_loss',
      occupation: 'homemaker',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'advanced',
      favorite_foods: 'Thepla, khichdi, kadhi, dal dhokli, undhiyu',
      breakfast: 'Thepla with chunda or pickle',
      lunch: 'Khichdi with kadhi',
      dinner: 'Roti, dal, and sabzi — sometimes dal dhokli',
      snacks: 'Handful of peanuts or fruit',
      timing_breakfast: '08:30',
      timing_lunch: '13:00',
      timing_dinner: '20:30',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['thepla', 'khichdi', 'kadhi'],
    mustExclude: ['quinoa', 'overnight oats', 'avocado'],
  },
  {
    id: 'early-gym-then-breakfast',
    label: '5:30am gym, breakfast after at 7:00',
    intent: 'Meal times must follow early training, not a 9am office breakfast',
    form: {
      name: 'Arjun Earlygym',
      gender: 'male',
      age: '24',
      weight: '75',
      height: '177',
      fitness_goal: 'muscle_gain',
      occupation: 'desk_job',
      preferred_workout_time: 'early_morning',
      training_days_per_week: '5',
      training_available_days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      diet_preference: 'eggetarian',
      egg_days: '4',
      chicken_days: '0',
      fish_days: '0',
      egg_allowed_days: ['monday', 'tuesday', 'thursday', 'friday'],
      chicken_allowed_days: [],
      fish_allowed_days: [],
      whey_protein: 'yes',
      cooking_ability: 'basic',
      favorite_foods: 'Eggs, oats, dal, roti, whey',
      breakfast: 'Post-workout oats with banana and whey, or eggs',
      lunch: 'Dal, roti, and curd',
      dinner: 'Egg curry or paneer with roti',
      snacks: 'Whey or fruit',
      timing_breakfast: '07:00',
      timing_lunch: '13:00',
      timing_dinner: '20:30',
      timing_snacks: '16:30',
      food_allergies: 'none',
      foods_disliked: 'None',
    },
    mustInclude: ['oats', 'egg', 'dal'],
    mustExclude: ['quinoa bowl', 'avocado toast'],
  },
  {
    id: 'late-it-shift',
    label: 'IT shift — dinner at 11pm',
    intent: 'Must keep a late dinner, not force 7–8pm “ideal” timing',
    form: {
      name: 'Rahul Lateit',
      gender: 'male',
      age: '27',
      weight: '84',
      height: '176',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      work_school_schedule: 'IT job 1pm–11pm. Wakes at 10am. Dinner after logging off around 11pm.',
      diet_preference: 'non_vegetarian',
      egg_days: '3',
      chicken_days: '2',
      fish_days: '0',
      egg_allowed_days: ['monday', 'wednesday', 'friday'],
      chicken_allowed_days: ['tuesday', 'saturday'],
      fish_allowed_days: [],
      whey_protein: 'yes',
      cooking_ability: 'minimal',
      favorite_foods: 'Eggs, chicken rice bowl, dal, Maggi',
      breakfast: 'Late breakfast — eggs and toast around 10:30',
      lunch: 'Office cafeteria rice and dal',
      dinner: 'Swiggy bowl or Maggi after 11pm',
      snacks: 'Office chai and biscuits',
      timing_breakfast: '10:30',
      timing_lunch: '15:30',
      timing_dinner: '23:00',
      timing_snacks: '18:30',
      food_allergies: 'none',
      foods_disliked: 'Olives',
    },
    mustInclude: ['egg', 'dal', 'rice'],
    mustExclude: ['quinoa', 'overnight oats'],
  },
  {
    id: 'busy-parent-leftovers',
    label: 'Busy parent — kids leftovers, 9:30pm dinner',
    intent: 'Must use leftover / kid-food reality, not a separate gourmet chart',
    form: {
      name: 'Meera Parent',
      gender: 'female',
      age: '37',
      weight: '72',
      height: '161',
      fitness_goal: 'fat_loss',
      occupation: 'homemaker',
      work_school_schedule: 'School drop 8am, pickup 3pm, kids bedtime 9pm. Cooks one pot for family.',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'comfortable',
      favorite_foods: 'Khichdi, dal, roti, kids pasta, banana',
      breakfast: 'Kids leftover paratha or poha while packing tiffins',
      lunch: 'Whatever I cooked for the kids — dal rice or khichdi',
      dinner: 'Family roti, dal, sabzi after kids eat',
      snacks: 'Chai and a biscuit while helping homework',
      timing_breakfast: '07:45',
      timing_lunch: '13:30',
      timing_dinner: '21:30',
      timing_snacks: '16:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['dal', 'roti', 'khichdi'],
    mustExclude: ['quinoa', 'smoothie bowl', 'overnight oats'],
    requireSnack: true,
  },
  {
    id: 'traveller-no-kitchen',
    label: 'Travelling consultant — hotels and dhabas',
    intent: 'Must be orderable / dhaba food, not home-cooked elaborate meals',
    form: {
      name: 'Karan Travel',
      gender: 'male',
      age: '34',
      weight: '81',
      height: '175',
      fitness_goal: 'fat_loss',
      occupation: 'other',
      work_school_schedule: 'Flies 3 days a week. Hotel breakfast, dhaba lunch, dinner from hotel restaurant.',
      diet_preference: 'eggetarian',
      egg_days: '5',
      chicken_days: '0',
      fish_days: '0',
      egg_allowed_days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      chicken_allowed_days: [],
      fish_allowed_days: [],
      whey_protein: 'yes',
      cooking_ability: 'minimal',
      favorite_foods: 'Eggs, dal tadka, roti, curd, banana',
      breakfast: 'Hotel omelette and toast',
      lunch: 'Dhaba dal tadka with roti',
      dinner: 'Hotel dal, rice, and salad',
      snacks: 'Banana and roasted chana from a shop',
      timing_breakfast: '08:00',
      timing_lunch: '14:00',
      timing_dinner: '21:00',
      timing_snacks: '17:30',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['omelette', 'dal', 'roti'],
    mustExclude: ['sous vide', 'meal prep containers', 'overnight oats baked'],
  },
  {
    id: 'street-food-mumbai',
    label: 'Mumbai street-food lifestyle',
    intent: 'Must work with vada pav / pav bhaji reality, not replace with a clean-eating chart',
    form: {
      name: 'Aarav Mumbai',
      gender: 'male',
      age: '23',
      weight: '70',
      height: '173',
      fitness_goal: 'body_recomposition',
      occupation: 'student',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'minimal',
      monthly_food_budget: '6000',
      favorite_foods: 'Vada pav, pav bhaji, misal, poha',
      breakfast: 'Vada pav or poha from stall',
      lunch: 'Mess thali or pav bhaji',
      dinner: 'Misal pav or dal rice',
      snacks: 'Cutting chai and bun maska',
      timing_breakfast: '09:00',
      timing_lunch: '14:00',
      timing_dinner: '22:00',
      timing_snacks: '18:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['poha', 'pav', 'dal'],
    mustExclude: ['quinoa', 'kale', 'avocado', 'smoothie bowl'],
    lowBudget: true,
  },
  {
    id: 'tuesday-fast',
    label: 'Religious Tuesday fast — fruit till sunset',
    intent: 'Tuesday must not be a normal full-calorie chart',
    form: {
      name: 'Ananya Fasttue',
      gender: 'female',
      age: '30',
      weight: '63',
      height: '159',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      favorite_foods: 'Dal, roti, sabzi, fruit, milk',
      breakfast: 'Poha on normal days',
      lunch: 'Dal roti sabzi on normal days',
      dinner: 'Roti and sabzi',
      snacks: 'Fruit',
      timing_breakfast: '08:30',
      timing_lunch: '13:30',
      timing_dinner: '20:30',
      timing_snacks: '17:00',
      diet_custom_notes:
        'I fast every Tuesday — only fruit and milk till sunset, then a light sabzi-roti dinner.',
      food_allergies: 'none',
      foods_disliked: 'None',
    },
    mustInclude: ['dal', 'roti'],
    mustExclude: ['chicken', 'egg'],
    fastingWeekday: 'tuesday',
  },
  {
    id: 'keto-failed',
    label: 'Keto already failed — wants normal Indian meals',
    intent: 'Must not re-prescribe keto / high-fat low-carb',
    form: {
      name: 'Vikram Ketofail',
      gender: 'male',
      age: '36',
      weight: '88',
      height: '178',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'non_vegetarian',
      egg_days: '3',
      chicken_days: '2',
      fish_days: '0',
      egg_allowed_days: ['monday', 'wednesday', 'friday'],
      chicken_allowed_days: ['tuesday', 'thursday'],
      fish_allowed_days: [],
      whey_protein: 'no',
      cooking_ability: 'basic',
      previous_diets_failed: 'Keto for 2 months — too restrictive, constipation, quit',
      favorite_foods: 'Rice, dal, roti, chicken curry',
      breakfast: 'Poha or eggs with roti',
      lunch: 'Rice, dal, and sabzi',
      dinner: 'Roti with chicken or dal',
      snacks: 'Chana',
      timing_breakfast: '08:30',
      timing_lunch: '13:30',
      timing_dinner: '21:00',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Cauliflower (ate too much on keto)',
    },
    mustInclude: ['rice', 'dal', 'roti'],
    mustExclude: ['keto', 'ketosis', 'cauliflower rice'],
  },
  {
    id: 'no-whey-basic-veg',
    label: 'Vegetarian, no whey, basic cooking',
    intent: 'Must not add whey shakes or fancy prep',
    form: {
      name: 'Sneha Nowhey',
      gender: 'female',
      age: '26',
      weight: '61',
      height: '160',
      fitness_goal: 'muscle_gain',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      favorite_foods: 'Paneer, dal, roti, rice, curd',
      breakfast: 'Besan chilla with chutney',
      lunch: 'Dal, roti, curd, salad',
      dinner: 'Palak paneer with roti',
      snacks: 'Curd with fruit',
      timing_breakfast: '08:00',
      timing_lunch: '13:00',
      timing_dinner: '20:30',
      timing_snacks: '16:30',
      food_allergies: 'none',
      foods_disliked: 'Olives',
    },
    mustInclude: ['chilla', 'dal', 'paneer'],
    mustExclude: ['whey', 'protein powder', 'isolate'],
  },
  {
    id: 'college-maggi-nights',
    label: 'College student — Maggi nights, skipped breakfast',
    intent: 'Must not invent a 6-meal bodybuilding chart',
    form: {
      name: 'Rohan College',
      gender: 'male',
      age: '19',
      weight: '58',
      height: '176',
      fitness_goal: 'muscle_gain',
      occupation: 'student',
      diet_preference: 'eggetarian',
      egg_days: '4',
      chicken_days: '0',
      fish_days: '0',
      egg_allowed_days: ['monday', 'tuesday', 'thursday', 'saturday'],
      chicken_allowed_days: [],
      fish_allowed_days: [],
      whey_protein: 'no',
      cooking_ability: 'minimal',
      monthly_food_budget: '5000',
      favorite_foods: 'Maggi, eggs, bread omelette, dal rice',
      breakfast: 'Usually skip — maybe tea',
      lunch: 'College canteen dal rice or bread omelette',
      dinner: 'Maggi or egg bhurji with bread',
      snacks: 'Biscuit with chai',
      timing_breakfast: '',
      timing_lunch: '13:30',
      timing_dinner: '22:30',
      timing_snacks: '18:00',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['egg', 'dal'],
    mustExclude: ['quinoa', 'avocado', 'salmon', 'overnight oats'],
    skipBreakfast: true,
    lowBudget: true,
  },
  {
    id: 'standing-retail-odd-hours',
    label: 'Retail standing job — lunch at 4pm',
    intent: 'Shift lunch at 16:00 must be kept, not moved to 1pm',
    form: {
      name: 'Neha Retail',
      gender: 'female',
      age: '28',
      weight: '67',
      height: '163',
      fitness_goal: 'fat_loss',
      occupation: 'standing_job',
      work_school_schedule: 'Mall retail 11am–8pm. Lunch break at 4pm. Dinner after 9pm.',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      favorite_foods: 'Poha, thepla, dal, rice',
      breakfast: 'Thepla packed from home with chai',
      lunch: 'Tiffin dal rice eaten during 4pm break',
      dinner: 'Roti and sabzi after reaching home',
      snacks: 'Roasted chana behind the counter',
      timing_breakfast: '10:30',
      timing_lunch: '16:00',
      timing_dinner: '21:30',
      timing_snacks: '13:00',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['thepla', 'dal', 'rice'],
    mustExclude: ['quinoa', 'smoothie'],
    requireSnack: true,
  },
  {
    id: 'vegan-south-no-ghee',
    label: 'Vegan South Indian — oil only, no ghee ever',
    intent: 'Ghee/butter/curd must not sneak in on sambar/rice meals',
    form: {
      name: 'Priya Vegansouth',
      gender: 'female',
      age: '29',
      weight: '60',
      height: '162',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegan',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'comfortable',
      favorite_foods: 'Idli, dosa, sambar, rice, poriyal, coconut chutney',
      breakfast: 'Idli with sambar and coconut chutney',
      lunch: 'Rice, sambar, and vegetable poriyal',
      dinner: 'Dosa with sambar or lemon rice',
      snacks: 'Sundal or fruit',
      timing_breakfast: '08:00',
      timing_lunch: '13:00',
      timing_dinner: '20:00',
      timing_snacks: '17:00',
      food_allergies: 'none',
      foods_disliked: 'Mushrooms',
    },
    mustInclude: ['idli', 'sambar', 'rice'],
    mustExclude: ['ghee', 'butter', 'curd', 'dahi', 'paneer', 'milk', 'yogurt', 'whey', 'honey'],
  },
  {
    id: 'high-stress-wedding',
    label: 'Wedding in 12 weeks, high stress, family dinners',
    intent: 'Must keep family dinner foods, not a crash-diet chart they cannot follow',
    form: {
      name: 'Kavya Wedding',
      gender: 'female',
      age: '27',
      weight: '73',
      height: '164',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      stress_level: 'high',
      goal_deadline: '12_weeks',
      biggest_struggle: 'family dinners and sweets',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      favorite_foods: 'Roti, dal, paneer, rice, family sweets on weekends',
      breakfast: 'Upma or poha',
      lunch: 'Office dabba — roti, sabzi, dal',
      dinner: 'Family meal — roti, dal, sabzi, sometimes paneer',
      snacks: 'Chai and rusk',
      timing_breakfast: '08:30',
      timing_lunch: '13:30',
      timing_dinner: '21:00',
      timing_snacks: '17:30',
      diet_custom_notes: 'Sunday family lunch is heavier — dal, rice, paneer, one sweet. Do not ban Sunday meals.',
      food_allergies: 'none',
      foods_disliked: 'Bitter gourd',
    },
    mustInclude: ['poha', 'dal', 'roti'],
    mustExclude: ['keto', 'juice cleanse', '800 kcal'],
  },
  {
    id: 'labour-physical-job',
    label: 'Physical labour — 6am breakfast, big lunch',
    intent: 'Must feed a physical job, not a sedentary 1800kcal office chart',
    form: {
      name: 'Rahul Labour',
      gender: 'male',
      age: '32',
      weight: '70',
      height: '168',
      fitness_goal: 'muscle_gain',
      occupation: 'physical_job',
      activity_level: 'very_active',
      daily_steps: 'over_10000',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      monthly_food_budget: '7000',
      favorite_foods: 'Paratha, dal, rice, buttermilk, banana',
      breakfast: 'Two parathas with pickle and chai before site',
      lunch: 'Big tiffin — rice, dal, sabzi',
      dinner: 'Roti, dal, sabzi',
      snacks: 'Banana and buttermilk on site',
      timing_breakfast: '06:00',
      timing_lunch: '13:00',
      timing_dinner: '20:30',
      timing_snacks: '16:00',
      food_allergies: 'none',
      foods_disliked: 'None',
    },
    mustInclude: ['paratha', 'dal', 'rice'],
    mustExclude: ['quinoa', 'avocado', 'smoothie bowl'],
    requireSnack: true,
  },
  {
    id: 'dislikes-plus-allergy-stack',
    label: 'Stacked dislikes + peanut allergy + no whey',
    intent: 'Must not sneak mushrooms, karela, or peanuts into “healthy” meals',
    form: {
      name: 'Isha Stacked',
      gender: 'female',
      age: '31',
      weight: '65',
      height: '160',
      fitness_goal: 'fat_loss',
      occupation: 'desk_job',
      diet_preference: 'vegetarian',
      ...dietReset,
      whey_protein: 'no',
      cooking_ability: 'basic',
      food_allergies: 'Nut allergy',
      foods_disliked: 'Mushrooms, bitter gourd, olives',
      favorite_foods: 'Idli, dal, roti, rice, paneer',
      breakfast: 'Idli with sambar',
      lunch: 'Dal, roti, and salad',
      dinner: 'Paneer bhurji with roti',
      snacks: 'Fruit and roasted chana',
      timing_breakfast: '08:00',
      timing_lunch: '13:30',
      timing_dinner: '20:30',
      timing_snacks: '17:00',
    },
    mustInclude: ['idli', 'dal', 'paneer'],
    mustExclude: ['mushroom', 'karela', 'bitter gourd', 'peanut', 'almond', 'cashew', 'whey'],
  },
]
