'use client'

import type { CSSProperties } from 'react'
import { useRouter } from 'next/navigation'
import {
  formatGeneratedBy,
  formatGeneratedFrom,
  getPlanVersionStatus,
  parsePlanMeta,
} from '@/lib/plan-metadata'
import { formatPlanDate } from '@/lib/plans'
import { colors } from '@/lib/coach-theme'
import type { Plan } from '@/types/database'

type PlanVersionHistoryProps = {
  plans: Plan[]
  currentPlanId: string
  coachName?: string | null
}

export function PlanVersionHistory({ plans, currentPlanId, coachName }: PlanVersionHistoryProps) {
  const router = useRouter()
  const sorted = [...plans].sort((a, b) => b.version - a.version)

  if (sorted.length === 0) {
    return <p style={{ margin: 0, color: colors.textMuted }}>No plan versions yet.</p>
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      {sorted.map((plan) => {
        const meta = parsePlanMeta(plan)
        const status = getPlanVersionStatus(plan)
        const isCurrent = plan.id === currentPlanId

        return (
          <button
            key={plan.id}
            type="button"
            onClick={() => !isCurrent && router.push(`/coach/plan/${plan.id}`)}
            style={{
              ...itemStyle,
              ...(isCurrent ? currentItemStyle : {}),
              cursor: isCurrent ? 'default' : 'pointer',
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start' }}>
              <div>
                <div style={{ fontWeight: 700, fontSize: 15, color: colors.textPrimary }}>
                  Version {plan.version}
                </div>
                <div style={{ fontSize: 13, color: colors.textSecondary, marginTop: 4 }}>
                  {plan.title}
                </div>
              </div>
              <StatusPill status={status} />
            </div>
            <div style={metaGrid}>
              <MetaItem label="Published" value={plan.delivered_at ? formatPlanDate(plan.delivered_at) : '—'} />
              <MetaItem label="Generated from" value={formatGeneratedFrom(meta, plan)} />
              <MetaItem label="Generated by" value={formatGeneratedBy(meta)} />
              <MetaItem label="Published by" value={plan.delivered_at ? (coachName ?? 'Coach') : '—'} />
            </div>
          </button>
        )
      })}
    </div>
  )
}

function StatusPill({ status }: { status: string }) {
  const styles: Record<string, CSSProperties> = {
    Active: { backgroundColor: colors.successMuted, color: colors.success },
    'AI Draft': { backgroundColor: colors.accentMuted, color: colors.accent },
    Archived: { backgroundColor: colors.bgElevated, color: colors.textMuted },
    Draft: { backgroundColor: colors.warningMuted, color: colors.warning },
  }
  const style = styles[status] ?? styles.Draft
  return (
    <span style={{
      ...style,
      padding: '4px 10px',
      borderRadius: 999,
      fontSize: 11,
      fontWeight: 700,
      whiteSpace: 'nowrap',
    }}>
      {status}
    </span>
  )
}

function MetaItem({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div style={{ fontSize: 11, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
        {label}
      </div>
      <div style={{ fontSize: 13, color: colors.textPrimary, marginTop: 2 }}>{value}</div>
    </div>
  )
}

const itemStyle: CSSProperties = {
  textAlign: 'left',
  width: '100%',
  padding: 16,
  borderRadius: 14,
  border: `1px solid ${colors.borderSubtle}`,
  backgroundColor: colors.bgElevated,
}

const currentItemStyle: CSSProperties = {
  borderColor: colors.accent,
  backgroundColor: colors.accentMuted,
}

const metaGrid: CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
  gap: 12,
  marginTop: 12,
}
