import type { CSSProperties } from 'react'

export const onboardingStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100dvh',
    backgroundColor: '#f8f9fb',
    padding: '16px 16px 100px',
    boxSizing: 'border-box',
  },
  card: {
    maxWidth: 520,
    margin: '0 auto',
    backgroundColor: 'white',
    borderRadius: 16,
    padding: '24px 20px 28px',
    boxShadow: '0 4px 24px rgba(26, 26, 46, 0.08)',
  },
  header: { marginBottom: 24 },
  title: { margin: 0, fontSize: 24, color: '#1a1a2e', lineHeight: 1.3 },
  subtitle: { color: '#666', marginTop: 8, lineHeight: 1.5, fontSize: 15 },
  progressMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    fontSize: 13,
    color: '#666',
  },
  progressBar: { height: 6, backgroundColor: '#eee', borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#e94560', borderRadius: 999, transition: 'width 0.3s ease' },
  sectionPills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 14,
  },
  sectionPill: {
    fontSize: 11,
    padding: '4px 8px',
    borderRadius: 999,
    backgroundColor: '#f0f0f0',
    color: '#888',
  },
  sectionPillActive: {
    backgroundColor: '#fde8ec',
    color: '#e94560',
    fontWeight: 600,
  },
  stepContent: { marginBottom: 8 },
  stepTitle: { margin: '0 0 6px 0', fontSize: 20, color: '#1a1a2e' },
  stepHint: { margin: '0 0 20px 0', color: '#666', fontSize: 14, lineHeight: 1.5 },
  privacyNotice: {
    margin: '0 0 20px 0',
    padding: '14px 16px',
    backgroundColor: '#f0f7ff',
    border: '1px solid #cce0ff',
    borderRadius: 10,
    color: '#334155',
    fontSize: 14,
    lineHeight: 1.55,
  },
  field: { marginBottom: 20 },
  label: { display: 'block', marginBottom: 8, fontWeight: 600, fontSize: 14, color: '#1a1a2e' },
  input: {
    width: '100%',
    padding: '14px 12px',
    border: '1px solid #e0e0e0',
    borderRadius: 10,
    fontSize: 16,
    boxSizing: 'border-box',
    backgroundColor: 'white',
  },
  textarea: {
    width: '100%',
    padding: '14px 12px',
    border: '1px solid #e0e0e0',
    borderRadius: 10,
    fontSize: 16,
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    resize: 'vertical',
    minHeight: 88,
  },
  row: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 },
  chipGrid: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  chip: {
    padding: '10px 14px',
    borderRadius: 999,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e0e0e0',
    backgroundColor: 'white',
    fontSize: 14,
    cursor: 'pointer',
    color: '#333',
    lineHeight: 1.3,
  },
  chipSelected: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e94560',
    backgroundColor: '#fde8ec',
    color: '#c73652',
    fontWeight: 600,
  },
  radioGrid: { display: 'grid', gridTemplateColumns: '1fr', gap: 10 },
  radioCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e0e0e0',
    borderRadius: 12,
    cursor: 'pointer',
    fontSize: 15,
  },
  radioCardSelected: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e94560',
    backgroundColor: '#fff8f9',
  },
  fixedActions: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    padding: '16px',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTop: '1px solid #eee',
    backdropFilter: 'blur(8px)',
  },
  actionsInner: {
    maxWidth: 520,
    margin: '0 auto',
    display: 'flex',
    gap: 10,
  },
  backBtn: {
    flex: '0 0 auto',
    padding: '14px 20px',
    backgroundColor: 'white',
    color: '#333',
    border: '1px solid #ddd',
    borderRadius: 10,
    cursor: 'pointer',
    fontSize: 16,
  },
  nextBtn: {
    flex: 1,
    padding: '14px 20px',
    backgroundColor: '#e94560',
    color: 'white',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 600,
  },
  error: {
    backgroundColor: '#fde8ea',
    color: '#9b1c31',
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    fontSize: 14,
  },
  saved: { fontSize: 12, color: '#2e7d32', textAlign: 'right' as const, marginTop: 4 },
  loading: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100dvh',
    fontSize: 18,
    color: '#666',
  },
  reviewSection: { marginBottom: 20, paddingBottom: 16, borderBottom: '1px solid #eee' },
  reviewTitle: { margin: '0 0 10px 0', fontSize: 16, fontWeight: 700, color: '#1a1a2e' },
  reviewRow: { display: 'flex', flexDirection: 'column', gap: 2, marginBottom: 8 },
  reviewLabel: { fontSize: 11, color: '#999', textTransform: 'uppercase', letterSpacing: '0.4px' },
  reviewValue: { fontSize: 14, color: '#333', lineHeight: 1.4 },
  editLink: {
    display: 'inline-block',
    marginTop: 6,
    fontSize: 13,
    color: '#e94560',
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    fontWeight: 600,
  },
  termsBox: { display: 'flex', gap: 12, alignItems: 'flex-start', fontSize: 14, lineHeight: 1.5, marginTop: 8 },
  photoGrid: { display: 'grid', gap: 16 },
  photoPreview: { fontSize: 13, color: '#2e7d32', marginTop: 6 },
  timingConfirmList: { display: 'grid', gap: 10, marginTop: 20 },
  timingConfirmRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '12px 14px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e0e0e0',
    borderRadius: 10,
    backgroundColor: '#fafafa',
  },
  timingConfirmRowDone: {
    borderColor: '#2e7d32',
    backgroundColor: '#f0fdf4',
  },
  timingConfirmLabel: { fontSize: 14, fontWeight: 600, color: '#1a1a2e' },
  timingConfirmTime: { fontSize: 13, color: '#666', marginTop: 2 },
  timingConfirmBtn: {
    padding: '8px 12px',
    borderRadius: 8,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e94560',
    backgroundColor: 'white',
    color: '#e94560',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  timingConfirmBtnDone: {
    borderColor: '#2e7d32',
    backgroundColor: '#2e7d32',
    color: 'white',
    cursor: 'default',
  },
}
