import type { CSSProperties } from 'react'
import { colors, spacing, radius } from '@/lib/design-tokens'

export const onboardingStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100dvh',
    backgroundColor: colors.bgPrimary,
    padding: `${spacing[3]}px ${spacing[3]}px 100px`,
    boxSizing: 'border-box',
  },
  card: {
    maxWidth: 520,
    margin: '0 auto',
    backgroundColor: colors.bgCard,
    borderRadius: radius.lg,
    padding: `${spacing[5]}px ${spacing[4]}px 28px`,
    border: `1px solid ${colors.borderSubtle}`,
  },
  header: { marginBottom: spacing[5] },
  title: { margin: 0, fontSize: 24, color: colors.textPrimary, lineHeight: 1.3, fontWeight: 800, letterSpacing: '-0.02em' },
  subtitle: { color: colors.textSecondary, marginTop: 8, lineHeight: 1.5, fontSize: 15 },
  progressMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    fontSize: 13,
    color: colors.textMuted,
  },
  progressBar: { height: 6, backgroundColor: colors.bgElevated, borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: colors.accent, borderRadius: 999, transition: 'width 0.3s ease' },
  sectionPills: { display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 14 },
  sectionPill: {
    fontSize: 11,
    padding: '4px 8px',
    borderRadius: 999,
    backgroundColor: colors.bgElevated,
    color: colors.textMuted,
  },
  sectionPillActive: {
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    fontWeight: 600,
  },
  progressSavedNotice: {
    margin: '16px 0 0',
    padding: '12px 14px',
    borderRadius: radius.sm,
    backgroundColor: colors.bgElevated,
    border: `1px solid ${colors.borderSubtle}`,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 1.5,
  },
  stepContent: { marginBottom: 8 },
  stepTitle: { margin: '0 0 6px 0', fontSize: 20, color: colors.textPrimary, fontWeight: 700 },
  stepHint: { margin: '0 0 20px 0', color: colors.textSecondary, fontSize: 14, lineHeight: 1.5 },
  privacyNotice: {
    margin: '0 0 20px 0',
    padding: '14px 16px',
    backgroundColor: colors.accentMuted,
    border: `1px solid rgba(52, 211, 153, 0.2)`,
    borderRadius: radius.sm,
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 1.55,
  },
  field: { marginBottom: spacing[4] },
  label: { display: 'block', marginBottom: 8, fontWeight: 600, fontSize: 14, color: colors.textSecondary },
  input: {
    width: '100%',
    padding: '14px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 16,
    boxSizing: 'border-box',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minHeight: 56,
  },
  textarea: {
    width: '100%',
    padding: '14px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 16,
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    resize: 'vertical',
    minHeight: 88,
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
  },
  row: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 },
  chipGrid: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  chip: {
    padding: '10px 14px',
    borderRadius: 999,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderSubtle,
    backgroundColor: colors.bgElevated,
    fontSize: 14,
    cursor: 'pointer',
    color: colors.textSecondary,
    lineHeight: 1.3,
    minHeight: 44,
  },
  chipSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
    color: colors.accent,
    fontWeight: 600,
  },
  radioGrid: { display: 'grid', gridTemplateColumns: '1fr', gap: 10 },
  radioCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderSubtle,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontSize: 15,
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minHeight: 56,
  },
  radioCardSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  fixedActions: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    padding: spacing[3],
    paddingBottom: `max(${spacing[3]}px, env(safe-area-inset-bottom))`,
    backgroundColor: colors.bgGlass,
    borderTop: `1px solid ${colors.divider}`,
    backdropFilter: 'blur(20px)',
  },
  actionsInner: {
    maxWidth: 520,
    margin: '0 auto',
    display: 'flex',
    gap: 10,
  },
  backBtn: {
    flex: '0 0 auto',
    padding: '14px 20px',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontSize: 16,
    minHeight: 56,
  },
  nextBtn: {
    flex: 1,
    padding: '14px 20px',
    backgroundColor: colors.accent,
    color: colors.textInverse,
    border: 'none',
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 600,
    minHeight: 56,
  },
  error: {
    backgroundColor: colors.dangerMuted,
    color: colors.danger,
    padding: spacing[2],
    borderRadius: radius.sm,
    marginBottom: spacing[3],
    fontSize: 14,
  },
  saved: { fontSize: 12, color: colors.success, textAlign: 'right' as const, marginTop: 4 },
  loading: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100dvh',
    fontSize: 18,
    color: colors.textSecondary,
    backgroundColor: colors.bgPrimary,
  },
  reviewSection: { marginBottom: spacing[4], paddingBottom: spacing[3], borderBottom: `1px solid ${colors.divider}` },
  reviewTitle: { margin: '0 0 10px 0', fontSize: 16, fontWeight: 700, color: colors.textPrimary },
  reviewRow: { display: 'flex', flexDirection: 'column', gap: 2, marginBottom: 8 },
  reviewLabel: { fontSize: 11, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: '0.4px' },
  reviewValue: { fontSize: 14, color: colors.textSecondary, lineHeight: 1.4 },
  editLink: {
    display: 'inline-block',
    marginTop: 6,
    fontSize: 13,
    color: colors.accent,
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    fontWeight: 600,
  },
  termsBox: { display: 'flex', gap: 12, alignItems: 'flex-start', fontSize: 14, lineHeight: 1.5, marginTop: 8, color: colors.textSecondary },
  photoGrid: { display: 'grid', gap: spacing[3] },
  photoPreview: { fontSize: 13, color: colors.success, marginTop: 6 },
  timingConfirmList: { display: 'grid', gap: 10, marginTop: spacing[4] },
  timingConfirmRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '12px 14px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderSubtle,
    borderRadius: radius.sm,
    backgroundColor: colors.bgElevated,
  },
  timingConfirmRowDone: {
    borderColor: colors.success,
    backgroundColor: colors.successMuted,
  },
  timingConfirmLabel: { fontSize: 14, fontWeight: 600, color: colors.textPrimary },
  timingConfirmTime: { fontSize: 13, color: colors.textMuted, marginTop: 2 },
  timingConfirmBtn: {
    padding: '8px 12px',
    borderRadius: 8,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.accent,
    backgroundColor: 'transparent',
    color: colors.accent,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    minHeight: 44,
  },
  timingConfirmBtnDone: {
    borderColor: colors.success,
    backgroundColor: colors.success,
    color: colors.textInverse,
    cursor: 'default',
  },
}
