import type { CSSProperties } from 'react'
import { colors, spacing, radius } from '@/lib/design-tokens'

export const adminStyles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', backgroundColor: colors.bgPrimary },
  container: { maxWidth: 1200, margin: '0 auto', padding: `${spacing[5]}px ${spacing[3]}px` },
  containerWide: { maxWidth: 1280, margin: '0 auto', padding: `${spacing[5]}px ${spacing[3]}px` },
  backLink: { display: 'inline-block', color: colors.accent, textDecoration: 'none', marginBottom: spacing[3], fontWeight: 600, fontSize: 14 },
  title: { margin: '0 0 6px 0', fontSize: 28, fontWeight: 800, color: colors.textPrimary, letterSpacing: '-0.02em' },
  subtitle: { margin: '0 0 24px 0', color: colors.textSecondary, fontSize: 15 },
  loading: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '50vh', fontSize: 18, color: colors.textSecondary },
  error: { backgroundColor: colors.dangerMuted, color: colors.danger, padding: 14, borderRadius: radius.sm, marginBottom: spacing[3], fontSize: 14, border: `1px solid rgba(239, 68, 68, 0.2)` },
  errorBox: { backgroundColor: colors.dangerMuted, color: colors.danger, padding: 28, borderRadius: radius.md, textAlign: 'center', border: `1px solid rgba(239, 68, 68, 0.2)` },
  empty: { backgroundColor: colors.bgCard, padding: 40, borderRadius: radius.md, textAlign: 'center', color: colors.textMuted, border: `1px solid ${colors.borderSubtle}` },
  card: { backgroundColor: colors.bgCard, padding: 22, borderRadius: radius.md, border: `1px solid ${colors.borderSubtle}`, marginBottom: spacing[3] },
  cardTitle: { margin: '0 0 16px 0', fontSize: 17, fontWeight: 700, color: colors.textPrimary },
  statGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: spacing[3], marginBottom: spacing[5] },
  statCard: {
    backgroundColor: colors.bgCard,
    padding: 20,
    borderRadius: radius.md,
    border: `1px solid ${colors.borderSubtle}`,
  },
  statLabel: { fontSize: 12, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 6 },
  statValue: { fontSize: 28, fontWeight: 800, color: colors.textPrimary, letterSpacing: '-0.02em' },
  statHint: { fontSize: 12, color: colors.textMuted, marginTop: 4 },
  toolbar: { display: 'flex', flexWrap: 'wrap', gap: spacing[2], marginBottom: spacing[4], alignItems: 'center' },
  searchInput: {
    flex: '1 1 220px',
    minWidth: 200,
    padding: '12px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 15,
    boxSizing: 'border-box',
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
  },
  select: {
    padding: '12px 16px',
    border: `1px solid ${colors.borderSubtle}`,
    borderRadius: radius.sm,
    fontSize: 14,
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    minWidth: 160,
  },
  tableWrap: { overflowX: 'auto', backgroundColor: colors.bgCard, borderRadius: radius.md, border: `1px solid ${colors.borderSubtle}` },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: { textAlign: 'left', padding: '14px 16px', borderBottom: `1px solid ${colors.divider}`, color: colors.textMuted, fontWeight: 600, fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.03em', whiteSpace: 'nowrap' },
  td: { padding: '14px 16px', borderBottom: `1px solid ${colors.divider}`, verticalAlign: 'middle', color: colors.textPrimary },
  linkBtn: { color: colors.accent, background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600, fontSize: 14, padding: 0, textDecoration: 'none' },
  primaryBtn: { padding: '12px 20px', backgroundColor: colors.accent, color: colors.textInverse, border: 'none', borderRadius: radius.sm, cursor: 'pointer', fontSize: 14, fontWeight: 600, minHeight: 48 },
  secondaryBtn: { padding: '12px 20px', backgroundColor: colors.bgElevated, color: colors.textPrimary, border: `1px solid ${colors.borderSubtle}`, borderRadius: radius.sm, cursor: 'pointer', fontSize: 14, fontWeight: 600, minHeight: 48 },
  badge: { display: 'inline-block', padding: '3px 10px', borderRadius: 12, fontSize: 12, fontWeight: 600 },
  badgeOk: { backgroundColor: colors.successMuted, color: colors.success },
  badgeWarn: { backgroundColor: colors.warningMuted, color: colors.warning },
  badgeMuted: { backgroundColor: colors.bgElevated, color: colors.textMuted },
  badgeInfo: { backgroundColor: colors.accentMuted, color: colors.accent },
  infoGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: spacing[3] },
  infoRow: { display: 'flex', flexDirection: 'column', gap: 4 },
  infoLabel: { fontSize: 11, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: '0.04em' },
  infoValue: { fontSize: 15, fontWeight: 500, color: colors.textPrimary },
  activityItem: { padding: '12px 0', borderBottom: `1px solid ${colors.divider}`, fontSize: 14, color: colors.textSecondary },
  activityTime: { fontSize: 12, color: colors.textMuted, marginTop: 4 },
  retryBtn: { marginTop: 12, padding: '12px 20px', backgroundColor: colors.bgElevated, color: colors.textPrimary, border: `1px solid ${colors.borderSubtle}`, borderRadius: radius.sm, cursor: 'pointer', minHeight: 48 },
}
