import type { CSSProperties } from 'react'

export const adminStyles: Record<string, CSSProperties> = {
  page: { minHeight: '100vh', backgroundColor: '#f4f5f8' },
  container: { maxWidth: 1200, margin: '0 auto', padding: '28px 20px' },
  containerWide: { maxWidth: 1280, margin: '0 auto', padding: '28px 20px' },
  backLink: { display: 'inline-block', color: '#7c3aed', textDecoration: 'none', marginBottom: 16, fontWeight: 600, fontSize: 14 },
  title: { margin: '0 0 6px 0', fontSize: 28, fontWeight: 700, color: '#1a1a2e' },
  subtitle: { margin: '0 0 24px 0', color: '#666', fontSize: 15 },
  loading: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '50vh', fontSize: 18, color: '#666' },
  error: { backgroundColor: '#fef2f2', color: '#991b1b', padding: 14, borderRadius: 10, marginBottom: 16, fontSize: 14 },
  errorBox: { backgroundColor: '#fef2f2', color: '#991b1b', padding: 28, borderRadius: 12, textAlign: 'center' },
  empty: { backgroundColor: 'white', padding: 40, borderRadius: 12, textAlign: 'center', color: '#666', boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
  card: { backgroundColor: 'white', padding: 22, borderRadius: 12, boxShadow: '0 1px 4px rgba(0,0,0,0.06)', marginBottom: 16 },
  cardTitle: { margin: '0 0 16px 0', fontSize: 17, fontWeight: 600, color: '#1a1a2e' },
  statGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16, marginBottom: 24 },
  statCard: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 12,
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    borderLeft: '4px solid #7c3aed',
  },
  statLabel: { fontSize: 12, color: '#888', textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 6 },
  statValue: { fontSize: 28, fontWeight: 700, color: '#1a1a2e' },
  statHint: { fontSize: 12, color: '#999', marginTop: 4 },
  toolbar: { display: 'flex', flexWrap: 'wrap', gap: 12, marginBottom: 20, alignItems: 'center' },
  searchInput: {
    flex: '1 1 220px',
    minWidth: 200,
    padding: '11px 14px',
    border: '1px solid #ddd',
    borderRadius: 8,
    fontSize: 15,
    boxSizing: 'border-box',
  },
  select: {
    padding: '11px 14px',
    border: '1px solid #ddd',
    borderRadius: 8,
    fontSize: 14,
    backgroundColor: 'white',
    minWidth: 160,
  },
  tableWrap: { overflowX: 'auto', backgroundColor: 'white', borderRadius: 12, boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: { textAlign: 'left', padding: '14px 16px', borderBottom: '1px solid #eee', color: '#666', fontWeight: 600, fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.03em', whiteSpace: 'nowrap' },
  td: { padding: '14px 16px', borderBottom: '1px solid #f0f0f0', verticalAlign: 'middle' },
  linkBtn: { color: '#7c3aed', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600, fontSize: 14, padding: 0, textDecoration: 'none' },
  primaryBtn: { padding: '11px 20px', backgroundColor: '#7c3aed', color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14, fontWeight: 600 },
  secondaryBtn: { padding: '11px 20px', backgroundColor: '#1a1a2e', color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14, fontWeight: 600 },
  badge: { display: 'inline-block', padding: '3px 10px', borderRadius: 12, fontSize: 12, fontWeight: 600 },
  badgeOk: { backgroundColor: '#d4edda', color: '#155724' },
  badgeWarn: { backgroundColor: '#fff3cd', color: '#856404' },
  badgeMuted: { backgroundColor: '#e2e3e5', color: '#383d41' },
  badgeInfo: { backgroundColor: '#e7f3ff', color: '#004085' },
  infoGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16 },
  infoRow: { display: 'flex', flexDirection: 'column', gap: 4 },
  infoLabel: { fontSize: 11, color: '#999', textTransform: 'uppercase', letterSpacing: '0.04em' },
  infoValue: { fontSize: 15, fontWeight: 500, color: '#333' },
  activityItem: { padding: '12px 0', borderBottom: '1px solid #f0f0f0', fontSize: 14, color: '#444' },
  activityTime: { fontSize: 12, color: '#999', marginTop: 4 },
  retryBtn: { marginTop: 12, padding: '10px 18px', backgroundColor: '#1a1a2e', color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer' },
}
